# Generated by Django 5.2.8 on 2025-11-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_category_book_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_publish', 'Can publish a post')]},
        ),
    ]
